name: test-workflow
on: workflow_dispatch
jobs: 
  one:
    runs-on: ubuntu-latest
    steps:
    - name: run hello world
      run: echo hello world
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - uses: actions/checkout@v3
    - run: python3 test.py
      
  
  
